### ISSUE TITLE
Propagative transmission

### ISSUE THREAD

**Issue by PhiBabs935** [DiseaseOntology/PathogenTransmissionOntology#3]
Is there are term in TRANS that is intended to cover propagative transmission? If not, could one be added? 

I and others needed such a term for the Virus Infectious Disease Ontology. See the discussion here: 
https://github.com/infectious-disease-ontology-extensions/ido-core/issues/13

**Comment by lschriml** [comment]
Hello Shane,
  Thank you for sending this request.
I will review and get back to you.
I appreciate your sharing the IDO discussion !!

Cheers,
Lynn

**Comment by lschriml** [comment]
Hello Shane @PhiBabs935, 
I've reviewed the terms. 
Please let me know what you think of the planned updates to TRANS:

Updates to vector-borne branch:
   - update name of vector-borne gastro-intestinal (TRANS:0000015)
          rename: biological transmission
            move previous name to be a synonym

  - Adding child terms to 'biological transmission'

**Child terms of biological transmission**

**propagative transmission** - when the organism ingested with the blood meal undergoes simple multiplication in the body of the vector

**cyclopropagative transmission** - he pathogen undergoes a developmental cycle (changes from one stage to another) as well as multiplication in the body of the vector
cyclodevelopmental transmission - pathogen undergoes developmental changes from one stage to another, but does not multiply

**transovarial transmission** -  transmitted from the female parent arthropod through the eggs to the offspring, the pathogen actually infects the developing egg

**vertical transmission** transmitted from the female parent through the eggs to the offspring, only the ovarial sheath and oviduct are infected, and the egg becomes infected as it passes down the oviduct and is inseminated.

**trans-stadial transmission** - newly hatched larval stages are infected with the pathogen, which is then transmitted to subsequent development stages of the vector

**veneral transmission** -  transfer the virus to uninfected female vectors in the seminal fluid during copulation.


**Sources:**
https://www.cdc.gov/csels/dsepd/ss1978/lesson1/section10.html
https://www.oie.int/doc/ged/D6818.PDF

Cheers,
Lynn

**Comment by lschriml** [comment]
TRANS has been updated.
